apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: btrdb/{{getenv DEVPREFIX}}console:{{.Env.TARGET_VERSION}}
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: BTRDB_ENDPOINTS
            value: btrdb-bootstrap:4410
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
          - name: admin-host-key
            mountPath: /etc/adminserver/
            readOnly: true
        ports:
          - containerPort: 2222
            protocol: TCP
            name: adminport
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
        - name: admin-host-key
          secret:
            secretName: admin-host-key
---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    app: console
spec:
  ports:
  - port: 2222
    targetPort: adminport
    name: console
  externalIPs:
    #here you should choose some IP addresses in your cluster that you
    #would like the admin console to be available on. Ensure that port
    #2222 is not already used on the machines these IPs route to
  selector:
    app: console
