# {{ .GenLine }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: console
  namespace: {{.TargetNamespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console
        image: btrdb/{{.Pfx}}console:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd-client:2379
          - name: BTRDB_ENDPOINTS
            value: btrdb-bootstrap:4410
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
          - name: admin-host-key
            mountPath: /etc/adminserver/
            readOnly: true
        ports:
          - containerPort: 2222
            protocol: TCP
            name: adminport
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
        - name: admin-host-key
          secret:
            secretName: admin-host-key
---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: {{.TargetNamespace}}
  labels:
    app: console
spec:
  ports:
  - port: 2222
    targetPort: adminport
    name: console
  externalIPs:{{range .SiteInfo.ExternalIPs}}
  - {{.}}{{end}}
  selector:
    app: console
