# {{ .GenLine }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apifrontend
  namespace: {{.TargetNamespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apifrontend
    spec:
      containers:
      - name: apifrontend
        image: btrdb/{{.Pfx}}apifrontend:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: DISABLE_INSECURE
            value: "NO"
          - name: BTRDB_ENDPOINTS
            value: btrdb-bootstrap:4410{{if gt (len .SiteInfo.ExternalIPs) 0 }}
          - name: EXTERNAL_ADDRESS
            value: {{ index .SiteInfo.ExternalIPs 0 }}{{end}}
        ports:
          - containerPort: 4410
            protocol: TCP
            name: grpc-insecure
          - containerPort: 4411
            protocol: TCP
            name: grpc-secure
          - containerPort: 9000
            protocol: TCP
            name: http
          - containerPort: 9001
            protocol: TCP
            name: https
---
apiVersion: v1
kind: Service
metadata:
  name: apifrontend
  namespace: {{.TargetNamespace}}
  labels:
    app: apifrontend
spec:
  ports:
  - port: 4410
    targetPort: grpc-insecure
    name: grpc-insecure
  - port: 4411
    targetPort: grpc-secure
    name: grpc-secure
  - port: 9000
    targetPort: http
    name: http
  - port: 9001
    targetPort: https
    name: https
  externalIPs:{{range .SiteInfo.ExternalIPs}}
  - {{.}}{{end}}
  selector:
    app: apifrontend
