---
apiVersion: v1
kind: Service
metadata:
  name: btrdb
  labels:
    app: btrdb
spec:
  ports:
  - port: 4410
    name: grpc
  - port: 9000
    name: http
  clusterIP: None
  selector:
    app: btrdb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: btrdb
spec:
  serviceName: "btrdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: btrdb
    spec:
      containers:
      - name: btrdb
        image: btrdb/{{getenv DEVPREFIX}}db:{{.Env.TARGET_VERSION}}
        resources:
          requests:
            cpu: "20"
            # changing this memory limit will not change how much memory
            # btrdb tries to use. That feature will come later
            memory: 96Gi
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: CEPH_HOT_POOL
            value: btrdb
          - name: CEPH_DATA_POOL
            value: btrdb
          - name: BTRDB_APPEND_ADVERTISE_GRPC
            value: compound-0.cs.berkeley.edu:4410
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
        ports:
        - containerPort: 4410
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
---
apiVersion: v1
kind: Service
metadata:
  name: btrdb-bootstrap
  labels:
    app: btrdb
spec:
  ports:
  - port: 4410
    targetPort: 4410
    name: grpc
  selector:
    app: btrdb
