# {{ .GenLine }}
#this creates the database in ceph. If you run this when there is an
#existing database, you will have a bad time.
apiVersion: batch/v1
kind: Job
metadata:
  name: btrdb-createdb
spec:
  template:
    metadata:
      name: btrdb-createdb
    spec:
      restartPolicy: Never
      containers:
      - name: btrdb-createdb
        image: btrdb/{{.Pfx}}db:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        args: [ "makedb" ]
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: CEPH_HOT_POOL
            value: {{.SiteInfo.Ceph.BTrDBPool}}
          - name: CEPH_DATA_POOL
            value: {{.SiteInfo.Ceph.BTrDBPool}}
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
