# {{ .GenLine }}
# this migrates from a single pool BTrDB to a tiered storage BTrDB
# it does not move the old data, but new data will be properly tiered.
apiVersion: batch/v1
kind: Job
metadata:
  name: btrdb-ensuredb
  namespace: {{.TargetNamespace}}
spec:
  template:
    metadata:
      name: btrdb-ensuredb
    spec:
      restartPolicy: Never
      containers:
      - name: btrdb-ensuredb
        image: btrdb/{{.Pfx}}db:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        args: [ "ensuredb" ]
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: CEPH_HOT_POOL
            value: {{.SiteInfo.Ceph.BTrDBHotPool}}
          - name: CEPH_DATA_POOL
            value: {{.SiteInfo.Ceph.BTrDBDataPool}}
          - name: CEPH_CONFIG
            value: {{.SiteInfo.Ceph.ConfigFile}}
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{ if .SiteInfo.Ceph.MountConfig }}
        volumeMounts:
        - name: ceph-config
          mountPath: {{.SiteInfo.Ceph.ConfigPath}}
          readOnly: true
      volumes:
      - name: ceph-config
        hostPath:
          path: {{.SiteInfo.Ceph.ConfigPath}}
          type: Directory
{{ else }}
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
{{ end }}
