# {{ .GenLine }}
# This file will instantiate a three node etcd cluster backed by
# emptyDir PVs. Basically if you delete the pods you will lose
# your data
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    protocol: TCP
    name: etcd-client-port
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: "etcd"
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        env:
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_DATA_DIR
          value: /srv/etcd
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "8589934592"
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: btrdb/etcd:3.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
        volumeMounts:
        - name: etcd-datadir
          mountPath: /srv/persist
  volumeClaimTemplates:
  - metadata:
      name: etcd-datadir
      labels:
        app: etcd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-backup
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-backup
    spec:
      containers:
      - name: backup
        image: btrdb/etcd:3.1.1
        args:
        - backup
        imagePullPolicy: Always
        env:
          - name: BACKUP_INTERVAL_SECS
            value: "21600"
        volumeMounts:
        - name: etcd-backup
          mountPath: /srv/persist
      volumes:
        - name: etcd-backup
          persistentVolumeClaim:
            claimName: etcd-backup
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
