# {{ .GenLine }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gepingress
  namespace: {{.TargetNamespace}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gepingress
  template:
    metadata:
      labels:
        app: gepingress
    spec:
      containers:
      - name: gepingress
        image: btrdb/{{.Pfx}}gepingress:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: BTRDB_ENDPOINTS
            value: btrdb-bootstrap:4410
          # This is approximately in bytes. The default is 1GB
          - name: WORK_QUEUE_LENGTH
            value: "1000000000"
          # This helps test work queue length. It adds a 10 second delay
          # to every database insert, which should back up the queue
          # enabling you to profile memory usage. Valid values:
          # YES or NO
          - name: DEBUG_DELAY_INSERTS
            value: "NO"
