# {{ .GenLine }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: receiver-upmu
  namespace: {{.TargetNamespace}}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: receiver-upmu
    spec:
      containers:
      - name: receiver
        image: btrdb/{{.Pfx}}receiver:{{.TargetVersion}}
        imagePullPolicy: {{.Containers.ImagePullPolicy}}
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: RECEIVER_PORT
            value: "1883"
          - name: RECEIVER_POOL
            value: {{.SiteInfo.Ceph.StagingPool}}
          - name: RECEIVER_GENERATION
            value: "10"
          - name: CEPH_CONFIG
            value: {{.SiteInfo.Ceph.ConfigFile}}
{{ if .SiteInfo.Ceph.MountConfig }}
        volumeMounts:
        - name: ceph-config
          mountPath: {{.SiteInfo.Ceph.ConfigPath}}
          readOnly: true
{{ else }}
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
{{ end }}
        ports:
        - containerPort: 1883
          protocol: TCP
          name: receiver-legacy
{{ if .SiteInfo.Ceph.MountConfig }}
      volumes:
      - name: ceph-config
        hostPath:
          path: {{.SiteInfo.Ceph.ConfigPath}}
          type: Directory
{{ else }}
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-upmu
  namespace: {{.TargetNamespace}}
  labels:
    app: receiver-upmu
spec:
  ports:
  - port: 1883
    targetPort: receiver-legacy
    name: receiver-legacy
  externalIPs:{{range .SiteInfo.ExternalIPs}}
  - {{.}}{{end}}
  selector:
    app: receiver-upmu
