apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  labels:
    app: etcd1
  name: "mysql-datat"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "30Gi"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: tst1
  labels:
    app: etcd1
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
