# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true



[[constraint]]
  branch = "master"
  name = "github.com/BTrDB/mr-plotter"

[[constraint]]
  branch = "master"
  name = "github.com/BTrDB/btrdb-server"

[[constraint]]
  branch = "master"
  name = "github.com/bcampbell/fuzzytime"

[[constraint]]
  branch = "master"
  name = "github.com/ceph/go-ceph"

[[constraint]]
  name = "github.com/coreos/etcd"
  branch = "master"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/crc16"

[[constraint]]
  name = "github.com/immesys/go-shellwords"
  branch = "master"

[[constraint]]
  name = "github.com/immesys/readline"
  branch = "master"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/samkumar/etcdstruct"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  branch = "v4"
  name = "gopkg.in/BTrDB/btrdb.v4"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v1"
  version = "1.0.22"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.32.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
