apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ottk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ottk
    spec:
      containers:
      - name: ottk
        image: btrdb/ottk:latest
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: ETCDCTL_API
            value: "3"
          - name: BTRDB_ENDPOINTS
            value: btrdb-bootstrap:4410
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
