apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: btrdbd
spec:
  # you can safely change this replication factor
  replicas: 4
  template:
    metadata:
      labels:
        app: btrdbd
    spec:
      containers:
      - name: btrdbd
        image: btrdb/k8s:latest
        resources:
          requests:
            cpu: "20"
            # changing this memory limit will not change how much memory
            # btrdb tries to use. That feature will come later
            memory: 96Gi
        env:
          - name: ETCD_ENDPOINT
            value: http://etcd:2379
          - name: CEPH_HOT_POOL
            value: btrdb
          - name: CEPH_DATA_POOL
            value: btrdb
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: ceph-keyring
            mountPath: /etc/ceph/
            readOnly: true
        ports:
        - containerPort: 4410
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
      volumes:
        - name: ceph-keyring
          secret:
            secretName: ceph-keyring
---
apiVersion: v1
kind: Service
metadata:
  name: btrdb-bootstrap
  labels:
    app: btrdbd
spec:
  ports:
  - port: 4410
    targetPort: 4410
    name: grpc
  selector:
    app: btrdbd
